language: swift
osx_image: xcode9.3beta
script:
 - xcodebuild -scheme Base32Encoder -project Base32Encoder.xcodeproj -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.3' build test
after_success:
 - bash <(curl -s https://codecov.io/bash)
