language: swift
osx_image: xcode9.3beta
script:
  - xcodebuild -project Base32Encoder.xcodeproj -scheme Base32Encoder -sdk iphonesimulator -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6S,OS=11.3" build test
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist
