env:
  global:
    - IOS_SCHEME="Base32Encoder"

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      env: PROJ="Base32Encoder.xcodeproj"  DESTINATION="OS=11.3,name=iPhone X" SCHEME="$IOS_SCHEME"

script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean build test -project "$PROJ" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist
