env:
  global:
    - IOS_SCHEME="Base32Encoder"

install:
  - gem install xcpretty

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      env: PROJ="Base32Encoder.xcodeproj"  DESTINATION="OS=11.3,name=iPhone X" SCHEME="$IOS_SCHEME"

script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean build test -project "$PROJ" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash cat ./Base32Encoder.framework.coverage.txt
  - bash cat ./Base32EncoderTests.xctest.coverage.txt 
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist
